// Данные карточек (продукты)
export const initialProducts = [
  // Home & Garden
  {
    id: "0",
    name: "Poäng Armchair",
    category: "Home & Garden",
    description: "A comfortable armchair with a unique design, perfect for relaxation.",
    rating: "4.7",
    price: "79.99",
    imgSrc: "../src/assets/products/product-1.avif",
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: "1",
    name: "MALM Bed Frame",
    category: "Home & Garden",
    description: "A sturdy bed frame with a minimalist design, available in various sizes.",
    rating: "4.3",
    price: "199.00",
    imgSrc: "../src/assets/products/product-2.jpg",
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: "2",
    name: "TÄRENDÖ Bench",
    category: "Home & Garden",
    description: "A simple and practical bench suitable for both indoor and outdoor use.",
    rating: "2.3",
    price: "29.99",
    imgSrc: "../src/assets/products/product-3.jpg",
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: "3",
    name: "HEMNES Bed Frame",
    category: "Home & Garden",
    description: "A classic bed frame with storage options and a timeless design.",
    rating: "3.8",
    price: "249.00",
    imgSrc: "../src/assets/products/product-4.jpg",
    isFavorite: false,
    cartQuantity: 1,
  },
  
  // Electronics
  {
    id: "4",
    name: "Smart TV 55 inch",
    category: "Electronics",
    description: "Enjoy stunning picture quality with this Smart TV.",
    rating: "4.5",
    price: "799.99",
    imgSrc: "../src/assets/products/product-5.jpg",
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: "5",
    name: "Wireless Headphones",
    category: "Electronics",
    description: "High-quality sound with noise cancellation.",
    rating: "4.8",
    price: "199.99",
    imgSrc: "../src/assets/products/product-6.jpg",
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: "6",
    name: "Smartphone XYZ",
    category: "Electronics",
    description: "Latest smartphone with amazing features.",
    rating: "4.5",
    price: "699.99",
    imgSrc: "../src/assets/products/product-7.jpg",
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: "7",
    name: "Laptop Pro 2023",
    category: "Electronics",
    description: "Powerful laptop with the latest specs for gaming and productivity.",
    rating: "4.6",
    price: "1299.99",
    imgSrc: "../src/assets/products/product-8.jpg",
    isFavorite: true,
    cartQuantity: 1,
  },
  
  // Fashion
  {
    id: "8",
    name: "Men's Jacket",
    category: "Fashion",
    description: "Stylish and warm jacket for winter.",
    rating: "4.2",
    price: "99.99",
    imgSrc: "../src/assets/products/product-9.jpg",
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: "9",
    name: "Women's Sneakers",
    category: "Fashion",
    description: "Comfortable sneakers for everyday wear.",
    rating: "4.4",
    price: "79.99",
    imgSrc: "../src/assets/products/product-10.jpg",
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: "10",
    name: "Classic Wristwatch",
    category: "Fashion",
    description: "Elegant wristwatch for every occasion.",
    rating: "4.9",
    price: "249.99",
    imgSrc: "../src/assets/products/product-11.jpg",
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: "11",
    name: "Summer Dress",
    category: "Fashion",
    description: "Light and breezy summer dress.",
    rating: "4.3",
    price: "49.99",
    imgSrc: "../src/assets/products/product-12.jpg",
    isFavorite: false,
    cartQuantity: 1,
  },
  
  // Sports
  {
    id: "12",
    name: "Yoga Mat",
    category: "Sports",
    description: "Non-slip mat for yoga and fitness.",
    rating: "4.8",
    price: "29.99",
    imgSrc: "../src/assets/products/product-13.jpg",
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: "13",
    name: "Dumbbell Set",
    category: "Sports",
    description: "Adjustable dumbbells for home workouts.",
    rating: "4.5",
    price: "119.99",
    imgSrc: "../src/assets/products/product-14.jpg",
    isFavorite: false,
    cartQuantity: 1,
  },
  {
    id: "14",
    name: "Running Shoes",
    category: "Sports",
    description: "Lightweight shoes for running.",
    rating: "4.7",
    price: "89.99",
    imgSrc: "../src/assets/products/product-15.jpg",
    isFavorite: true,
    cartQuantity: 1,
  },
  {
    id: "15",
    name: "Fitness Tracker",
    category: "Sports",
    description: "Track your workouts and health metrics.",
    rating: "4.6",
    price: "49.99",
    imgSrc: "../src/assets/products/product-16.jpg",
    isFavorite: false,
    cartQuantity: 1,
  },
];
